repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.11
      hooks:
          - id: ruff # Run the linter
            types_or: [python, pyi, jupyter]
            args: [--fix]
          - id: ruff-format # Run the formatter
            types_or: [python, pyi, jupyter]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
          - id: check-symlinks
          - id: check-yaml
            args: ["--unsafe"]
          - id: end-of-file-fixer
          - id: pretty-format-json
            args:
                - "--autofix"
                - "--indent=2"
                - "--no-sort-keys"
          - id: trailing-whitespace
